Repository elastic/elastic-package, pull requests merged in 2021-06, with the labels that each got.

#373 fix warn logger call
  internal/install/version_file.go
Labels: bug

#382 Don't use go get for tools in go.mod
  Makefile
Labels: Team:Integrations, ci

#381 Print summary table after errors
  internal/testrunner/reporters/formats/human.go
Labels: Team:Integrations

#386 Add support for constant_keyword "value" in field definition
  go.mod
  go.sum
  internal/fields/model.go
  internal/fields/testdata/constant-keyword-invalid.json
  internal/fields/testdata/constant-keyword-valid.json
  internal/fields/testdata/fields/fields.yml
  internal/fields/validate.go
  internal/fields/validate_test.go
Labels: enhancement

#390 Add Debug statement for running test name
  internal/testrunner/runners/system/runner.go
Labels: enhancement

#397 Avoid trying to adjust dropped events on test results
  internal/testrunner/runners/pipeline/test_result.go
Labels: Team:Integrations
