Repository elastic/elastic-package, pull requests merged in 2021-09, with the labels that each got.

#486 Fix null pointer exception when build.yml is missing
  internal/fields/dependency_manager.go
Labels: bug, Team:Integrations

#487 Filter directory listings by extension
  internal/builder/external_fields.go
  internal/docs/readme.go
  internal/fields/validate.go
  internal/packages/assets.go
  internal/testrunner/runners/pipeline/ingest_pipeline.go
  internal/testrunner/runners/system/servicedeployer/kubernetes.go
Labels: Team:Integrations

#493 fix: add elastic-agent as available service
  cmd/stack.go
  cmd/stack_test.go
Labels: bug

#518 [CI] use obltGitHubComments
  .ci/Jenkinsfile
Labels: automation

#524 Update stack.go
  README.md
  cmd/stack.go
Labels: documentation
