Repository elastic/elastic-package, pull requests merged in 2021-12, with the labels that each got.

#602 [mergify] use merge queue
  .mergify.yml
Labels: automation, Team:Automation

#613 Report error root cause if available
  internal/elasticsearch/error.go
  internal/elasticsearch/error_test.go
Labels: enhancement, Team:Security-External Integrations, Team:Ecosystem

#596 Remove ambiguous elasticsearch imports
  cmd/testrunner.go
  internal/elasticsearch/client.go
  internal/testrunner/runners/asset/runner.go
  internal/testrunner/runners/pipeline/ingest_pipeline.go
  internal/testrunner/runners/pipeline/runner.go
  internal/testrunner/runners/system/runner.go
  internal/testrunner/testrunner.go
Labels: Team:Ecosystem, technnical debt

#634 Upgrade k8s version to the latest one (v1.23.0)
  .ci/Jenkinsfile
Labels: Team:Integrations
