Repository elastic/elastic-package, pull requests merged in 2021-07, with the labels that each got.

#401 Add missing new line in test report
  internal/testrunner/reporters/formats/human.go
Labels: Team:Integrations

#400 Delete volumes when running docker compose down
  docs/howto/system_testing.md
  internal/stack/compose.go
  internal/testrunner/runners/system/servicedeployer/compose.go
Labels: Team:Integrations

#420 Add watch of jobs resources in cluster role used by agent
  internal/install/static_kubernetes_elastic_agent_yml.go
Labels: Team:Integrations, enhancement

#423 [dependabot][mergify] automate merge and add reviewers
  .github/dependabot.yml
  .mergify.yml
Labels: automation

#426 Add note about authorizing tokens to use the Elastic organization
  README.md
  tools/readme/readme.md.tmpl
Labels: Team:Integrations
