Repository elastic/elastic-package, pull requests merged in 2022-01, with the labels that each got.

#639 Refactor pipelineResource into a separate package
  internal/elasticsearch/ingest/pipeline.go
  internal/elasticsearch/ingest/pipeline_test.go
  internal/testrunner/runners/pipeline/ingest_pipeline.go
  internal/testrunner/runners/pipeline/runner.go
Labels: enhancement, Team:Elastic-Agent, Team:Security-External Integrations

#644 internal/testrunner/runners/pipeline: output documents with fields in a normalized order
  internal/testrunner/runners/pipeline/test_result.go
Labels: enhancement, Team:Elastic-Agent, Team:Security-External Integrations

#648 internal/version: make version available when installed via go install github.com/elastic/elastic-package
  internal/version/version.go
Labels: Team:Ecosystem

#652 Neutral naming for elastic-package
  .mergify.yml
  README.md
  cmd/build.go
  cmd/create.go
  cmd/stack.go
  cmd/testrunner.go
  docs/howto/create_new_package.md
  docs/howto/system_testing.md
  internal/fields/validate.go
  tools/readme/readme.md.tmpl
Labels: automation

#656 Extract processors from an ingest.Pipeline
  internal/elasticsearch/ingest/processors.go
  internal/elasticsearch/ingest/processors_test.go
Labels: enhancement, Team:Security-External Integrations, Team:Ecosystem
