Repository elastic/elastic-package, pull requests merged in 2022-03, with the labels that each got.

#704 Generate a cobertura report for processors in pipeline tests
  cmd/testrunner.go
  internal/testrunner/coverageoutput.go
  internal/testrunner/coverageoutput_test.go
  internal/testrunner/runners/pipeline/coverage.go
  internal/testrunner/runners/pipeline/runner.go
  internal/testrunner/testrunner.go
Labels: Team:Integrations, Team:Security-External Integrations, Team:Ecosystem

#743 Compare test results using json diff
  go.mod
  go.sum
  internal/testrunner/runners/pipeline/runner_test.go
  internal/testrunner/runners/pipeline/test_result.go
  internal/testrunner/runners/pipeline/test_result_test.go
  test/packages/other/number_formats/changelog.yml
  test/packages/other/number_formats/data_stream/numbers/_dev/test/pipeline/test-example.log
  test/packages/other/number_formats/data_stream/numbers/_dev/test/pipeline/test-example.log-expected.json
  test/packages/other/number_formats/data_stream/numbers/agent/stream/stream.yml.hbs
  test/packages/other/number_formats/data_stream/numbers/elasticsearch/ingest_pipeline/default.yml
  test/packages/other/number_formats/data_stream/numbers/fields/base-fields.yml
  test/packages/other/number_formats/data_stream/numbers/fields/fields.yml
  test/packages/other/number_formats/data_stream/numbers/manifest.yml
  test/packages/other/number_formats/docs/README.md
  test/packages/other/number_formats/img/sample-logo.svg
  test/packages/other/number_formats/img/sample-screenshot.png
  test/packages/other/number_formats/manifest.yml
Labels: discuss

#759 Create add-to-ecosystem-project.yml
  .github/workflows/add-to-ecosystem-project.yml
Labels: Team:Ecosystem

#766 Import ecs fields from the ecs_nested.yml source file
  internal/fields/dependency_manager.go
  internal/fields/model.go
  test/packages/other/fields_tests/data_stream/first/fields/geo-fields.yml
  test/packages/other/fields_tests/data_stream/first/sample_event.json
  test/packages/other/fields_tests/docs/README.md
Labels: Team:Ecosystem

#770 Add tags for added and removed content in jsondiff
  internal/testrunner/runners/pipeline/test_result.go
Labels: Team:Ecosystem
