Repository elastic/elastic-package, pull requests merged in 2022-02, with the labels that each got.

#670 Export installed objects for a given package
  .gitignore
  README.md
  cmd/dump.go
  cmd/root.go
  internal/cobraext/const.go
  internal/common/helpers.go
  internal/common/helpers_test.go
  internal/dump/componenttemplates.go
  internal/dump/ilmpolicies.go
  internal/dump/indextemplates.go
  internal/dump/ingestpipelines.go
  internal/dump/installedobjects.go
  internal/dump/installedobjects_test.go
  internal/dump/testdata/apache-dump-all/component_templates/.fleet_component_template-1.json
  internal/dump/testdata/apache-dump-all/component_templates/logs-apache.access@custom.json
  internal/dump/testdata/apache-dump-all/component_templates/logs-apache.access@settings.json
  internal/dump/testdata/apache-dump-all/component_templates/logs-apache.error@custom.json
  internal/dump/testdata/apache-dump-all/component_templates/logs-apache.error@settings.json
  internal/dump/testdata/apache-dump-all/component_templates/metrics-apache.status@custom.json
  internal/dump/testdata/apache-dump-all/component_templates/metrics-apache.status@settings.json
  internal/dump/testdata/apache-dump-all/ilm_policies/logs.json
  internal/dump/testdata/apache-dump-all/ilm_policies/metrics.json
  internal/dump/testdata/apache-dump-all/index_templates/logs-apache.access.json
  internal/dump/testdata/apache-dump-all/index_templates/logs-apache.error.json
  internal/dump/testdata/apache-dump-all/index_templates/metrics-apache.status.json
  internal/dump/testdata/apache-dump-all/ingest_pipelines/.fleet_final_pipeline-1.json
  internal/dump/testdata/apache-dump-all/ingest_pipelines/logs-apache.access-1.3.4-third-party.json
  internal/dump/testdata/apache-dump-all/ingest_pipelines/logs-apache.access-1.3.4.json
  internal/dump/testdata/apache-dump-all/ingest_pipelines/logs-apache.error-1.3.4-third-party.json
  internal/dump/testdata/apache-dump-all/ingest_pipelines/logs-apache.error-1.3.4.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_component_template-.fleet_component_template-1.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_component_template-logs-apache.access@custom.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_component_template-logs-apache.access@settings.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_component_template-logs-apache.error@custom.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_component_template-logs-apache.error@settings.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_component_template-metrics-apache.status@custom.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_component_template-metrics-apache.status@settings.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_ilm-policy-logs.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_ilm-policy-metrics.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_index_template-*-apache.*.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_ingest-pipeline-.fleet_final_pipeline-1.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_ingest-pipeline-logs-apache.access-1.3.4-third-party.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_ingest-pipeline-logs-apache.access-1.3.4.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_ingest-pipeline-logs-apache.error-1.3.4-third-party.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/_ingest-pipeline-logs-apache.error-1.3.4.json
  internal/dump/testdata/elasticsearch-mock-dump-apache/root.json
  internal/elasticsearch/client.go
  internal/elasticsearch/test/httptest.go
  internal/export/dashboards_test.go
  internal/export/testdata/system-navigation.json
Labels: Team:Ecosystem

#685 Remove wildcards from file names
  internal/dump/testdata/elasticsearch-mock-dump-apache/_index_template-_-apache._.json
  internal/elasticsearch/test/httptest.go
Labels: Team:Ecosystem

#689 Add GetPipelineStats() method to testrunner package
  internal/elasticsearch/ingest/nodestats.go
  internal/elasticsearch/ingest/nodestats_test.go
Labels: Team:Integrations, Team:Security-External Integrations, Team:Ecosystem

#702 Add cronjobs in clusterRole for k8s runner
  internal/testrunner/runners/system/servicedeployer/elastic-agent-managed.yaml.tmpl
Labels: Team:Cloudnative-Monitoring
