Repository elastic/elastic-package, pull requests merged in 2023-04, with the labels that each got.

#1226 Add catalog information to define pipelines as a Backstage Resource
  catalog-info.yaml
Labels: ci

#1236 docker-compose config - bind mount /run/service_logs/ in Agent container
  internal/stack/_static/docker-compose-stack.yml.tmpl
Labels: Team:Ecosystem

#1240 Add techdocs annotation for elastic-package
  catalog-info.yaml
Labels: ci

#1233 Use latest docker-compose v2 version
  .buildkite/pipeline.yml
  .buildkite/scripts/integration_tests.sh
  internal/compose/compose.go
Labels: ci

#1241 Replace techdocs with link to our Documentation
  catalog-info.yaml
Labels: enhancement, ci
